### ISSUE TITLE
Error in UK_Waypoints

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-content#30]
`/home/travis/build/XCSoar/xcsoar-data-content/waypoints/Turkey.cup
/home/travis/build/XCSoar/xcsoar-data-content/waypoints/United_Kingdom.cup
Traceback (most recent call last):
  File "/home/travis/build/XCSoar/xcsoar-data-content/scripts/check-waypoints", line 10, in <module>
    cupfile.read(open(str(sys.argv[1])))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/aerofiles/seeyou/reader.py", line 57, in read
    waypoint = self.decode_waypoint(fields)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/aerofiles/seeyou/reader.py", line 93, in decode_waypoint
    'frequency': self.decode_frequency(fields[9]),
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/aerofiles/seeyou/reader.py", line 216, in decode_frequency
    raise ParserError('Reading frequency failed')
aerofiles.errors.ParserError: Reading frequency failed
/home/travis/build/XCSoar/xcsoar-data-content/waypoints/United_States.cup
/home/travis/build/XCSoar/xcsoar-data-content/waypoints/Uzbekistan.cup
/home/travis/build/XCSoar/xcsoar-data-content/waypoints/xcsoar_waypoints.cup
Traceback (most recent call last):
  File "/home/travis/build/XCSoar/xcsoar-data-content/scripts/check-waypoints", line 10, in <module>
    cupfile.read(open(str(sys.argv[1])))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/aerofiles/seeyou/reader.py", line 57, in read
    waypoint = self.decode_waypoint(fields)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/aerofiles/seeyou/reader.py", line 93, in decode_waypoint
    'frequency': self.decode_frequency(fields[9]),
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/aerofiles/seeyou/reader.py", line 216, in decode_frequency
    raise ParserError('Reading frequency failed')
aerofiles.errors.ParserError: Reading frequency failed
/home/travis/build/XCSoar/xcsoar-data-content/waypoints/Zambia.cup
/home/travis/build/XCSoar/xcsoar-data-content/waypoints/Zimbabwe.cup
The command "for each in $TRAVIS_BUILD_DIR/waypoints/*.cup ; do python $TRAVIS_BUILD_DIR/scripts/check-waypoints "${each}" ; done" exited with 0.`

**Comment by lordfolken** [comment]
CI still passes with return code 0.

**Comment by lordfolken** [comment]
Fixed by #33
